// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Elinext.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 7, 29, 22, 2, 27, 914, DateTimeKind.Local).AddTicks(9068),
                            Message = "Comment",
                            PostId = 1,
                            Username = "KOTKenny"
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 1,
                            CreateDate = new DateTime(2021, 7, 29, 22, 2, 27, 914, DateTimeKind.Local).AddTicks(9657),
                            Message = "Reply",
                            Username = "George"
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 2,
                            CreateDate = new DateTime(2021, 7, 29, 22, 2, 27, 915, DateTimeKind.Local).AddTicks(195),
                            Message = "ReplyOfReply",
                            Username = "Daly"
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 3,
                            CreateDate = new DateTime(2021, 7, 29, 22, 2, 27, 915, DateTimeKind.Local).AddTicks(215),
                            Message = "ReplyOfReplyOfRely",
                            Username = "Minsy"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2021, 7, 29, 22, 2, 27, 915, DateTimeKind.Local).AddTicks(217),
                            Message = "Comment",
                            PostId = 1,
                            Username = "Oleg"
                        });
                });

            modelBuilder.Entity("DAL.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Article = "This is new post",
                            CreateDate = new DateTime(2021, 7, 29, 22, 2, 27, 911, DateTimeKind.Local).AddTicks(3181),
                            Title = "This is Title of Post"
                        });
                });

            modelBuilder.Entity("DAL.Models.Comment", b =>
                {
                    b.HasOne("DAL.Models.Comment", null)
                        .WithMany("Comments")
                        .HasForeignKey("CommentId");

                    b.HasOne("DAL.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DAL.Models.Comment", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DAL.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
